{% set name = "python-mumps" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_mumps-{{ version }}.tar.gz
  sha256: bb10a6bb3fd1522ed5771b832f99ed0c590b2524d5ae672cbb1b7348634be550

build:
  skip: true  # [py<39 or python_impl == 'pypy']
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - ninja                                  # [unix]
    - pkg-config                             # [unix]
  host:
    - python
    - cython
    - meson
    - meson-python
    - numpy
    - mumps-seq
    - setuptools-scm
    - pip
    - python-build
  run:
    - python
    - scipy >=1.8
    - mumps-seq

test:
  imports:
    - mumps
  commands:
    - pip check
    - python -c "import mumps; mumps.test()"
  requires:
    - pip
    - pytest

about:
  home: https://gitlab.kwant-project.org/kwant/python-mumps
  summary: Bindings and Python interface for the MUMPS sparse solver
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akhmerov
