{% set name = "python-mumps" %}
{% set version = "0.0.1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_mumps-{{ version }}.tar.gz
  sha256: 58bf081147c7a4c8fb80ca30a5f5008bd816bc6349fd969edad8dda058648bdb

build:
  skip: true  # [py<39 or python_impl == 'pypy']
  number: 7

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja                                  # [unix]
    - pkg-config                             # [unix]
  host:
    - python
    - cython
    - meson
    - meson-python
    - numpy
    - mumps-seq
    - setuptools-scm
    - pip
    - python-build
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='1.23') }}
    - scipy >=1.8
    - mumps-seq

test:
  imports:
    - mumps
  commands:
    - pip check
    - python -c "import mumps; mumps.test()"
  requires:
    - pip
    - pytest

about:
  home: https://gitlab.kwant-project.org/kwant/python-mumps
  summary: Bindings and Python interface for the MUMPS sparse solver
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akhmerov
